apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      nodeSelector:
        node-role: light
      enableServiceLinks: false    # disabilita iniezione env var dei Service
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          ports:
            - containerPort: 8000
          env:
            - name: PAPERLESS_REDIS
              value: redis://redis.databases.svc.cluster.local:6379
            - name: PAPERLESS_DBHOST
              value: postgres.databases.svc.cluster.local
            - name: PAPERLESS_DBPORT
              value: "5432"
            - name: PAPERLESS_DBNAME
              value: paperless
            - name: PAPERLESS_DBUSER
              value: paperless
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: db-password
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: secret-key
            - name: PAPERLESS_URL
              value: "https://paperless.mbianchi.me"
            - name: PAPERLESS_TIME_ZONE
              value: "Europe/Rome"
            - name: PAPERLESS_OCR_LANGUAGE
              value: "ita+eng"
            - name: PAPERLESS_CONSUMPTION_DIR
              value: /consume
            - name: PAPERLESS_DATA_DIR
              value: /data
            - name: PAPERLESS_MEDIA_ROOT
              value: /media
            - name: USERMAP_UID
              value: "1000"
            - name: USERMAP_GID
              value: "1000"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: media
              mountPath: /media
            - name: consume
              mountPath: /consume
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: media
          persistentVolumeClaim:
            claimName: paperless-media
        - name: consume
          nfs:
            server: 10.0.20.12
            path: /mnt/media/documents
