---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-oidc
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: AgApVNnOuT/oPXUXcjKFqmTvSBufj1VCQhrhfjsV2UMgEHBG/fVXsSROpr4ImmXdYXtMTxlLIA4IIreB2pquSLo29HauI9TsL/MJ1NMQkcjPR2yZXfaSdWtTWIK+V3XOB5KZ6/50rJmjwM+LEyt4bzrBPyChpx+Y+b/qcRbmadzJ6Xkt6NSs8S77L2FV1MnLsslug6C6mRGqTgw+XQUnHHDkqpySFhegn98C0RRVDljJC8p+t2OYfi/tP94UTpm+IqUCXSFvUuseJ5Av6nQ1zwwU0OJbQxRwEeiRe8nq2F4qqBvfR28vbN0oLpIK4Ss6gvP3vuqVY7dsj21Jki9/vmafxlXl+rsR7Sqoo+UHdJNn5vQiG2UBvUciKONf1yZUinMJqjWrRd763asYC2HumzOYMJdwuXGVXbeHE+hECtMMpWuzHUX50ZEc5LRBkQsxmz0CQOTxEKKdJWVwEiwDD29W/A50PdH5LWasB6iK50sS2CXMdjsA8NLMfeFqCpAXY3SBCGVo6krl2dnotlQg8rERoqCvwvlUUE26kFHDbOOHVUDDD1JT7BfvqQJGDw/U4GJVw91/PLXW7qjIt3l8/cSr0triHdb6KoTbV1itMIboTprLAGJn8+5N+mOmiGlfGvtKZuuG7yMEr01DkcXMTQl75MkxGHfEQ0O6M3Pvxi2p6ae2vIXoUH6jUkZxIYMyTDcV6VurMGkzNUm0B0Gz+ZvYqLdfjPFDfHX+s3/0Z4315wOglzWVrFhoTd0H7Xyi1Zmw+sN34WZzyCENUvhheo52Dha0mIiUFX81J6KdUsiWL0/gQ0Iur39YqwjS2VwZ1/2rHj0awMcno7hlENHVxoVqplZYQMkP/Y9PAQ9A61WWIpMRHVp5o1n5disYiELqZK/jeRKTkBM6Qb0TM3uCNhjeXssyJbQsWdT0PbEQH+shVjn/Dluv29BWFkza0kqlSgUvzLtt678wOiRQYpv6QUfb/vSZeLqAcgbgfRB6/ty0I5ES1hA778PfrKZK0ihBvClZiQ0Ioe1kk6RGCc9Ftw0REfc7ytQjANoUD9+wcB+m2x+h1JClt+zz1mRaCiWpSt1tbeYUJo8KJa9PaekvIVd1bPciOfDC2g7sU38bLj6/h0OhRGnXH5wMeud/5YUY6v12Ja9QFHmjGh1FEghPoW9HEC9maaY9nzomws1wl0Fs4n6uUx3HY/v7ESy8wvXn/LVKNA8BQkGZnSbVSsb1Z3d+20SMKkbG+y7+h/gdKO9W2dn4ZVyd9/4p39eeu6/xW7WNwXax6NVBtWwn1rge0IlULJmtOMciYqKjD18/oHeav4le
  template:
    metadata:
      name: paperless-oidc
      namespace: paperless
