apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage
  namespace: nextcloud
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-media
  resources:
    requests:
      storage: 1Ti
