apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeSelector:
        node-role: heavy
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          ports:
            - containerPort: 32400
              name: web
          env:
            - name: TZ
              value: "Europe/Rome"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-claim
                  key: token
            - name: ADVERTISE_IP
              value: "https://plex.mbianchi.me:443/"
            - name: ALLOWED_NETWORKS
              value: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
            - name: PLEX_UID
              value: "1000"
            - name: PLEX_GID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
              readOnly: true
            - name: transcode
              mountPath: /transcode
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 4Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: media
          nfs:
            server: 10.0.20.12
            path: /mnt/media
            readOnly: true
        - name: transcode
          emptyDir:
            sizeLimit: 20Gi
