apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # ArgoCD usa gRPC — l'ingress deve fare passthrough TLS al server
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    # Whitelist VPN — ArgoCD raggiungibile solo dalla VPN
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.42.0.0/16,10.0.20.0/24,10.8.0.0/24,10.0.10.0/24"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [argo.mbianchi.me]
      secretName: argocd-tls
  rules:
    - host: argo.mbianchi.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
