apiVersion: v1
kind: Service
metadata:
  name: wg-easy-vpn
  namespace: wireguard
spec:
  type: NodePort
  selector:
    app: wg-easy
  ports:
    - name: wireguard
      protocol: UDP
      port: 51820
      targetPort: 51820
      nodePort: 31820  # porta esposta sui nodi
---
apiVersion: v1
kind: Service
metadata:
  name: wg-easy-ui
  namespace: wireguard
spec:
  selector:
    app: wg-easy
  ports:
    - port: 51821
      targetPort: 51821
