---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgANAF3DAFmquclaxYB/Puq6Qk/0D4J8tZW8iOzehiRgN/ASXEaZhUFEk/2rrx7BrbAdHWlxEofdFosn+8zAWYPiLlxiMhZrbF5ioOyRbUJPoaSMkpFmvauFXWnxaSr1IJiKoxeXEEUJhO3sqehPoroiZkVvIbBcpL/m/5I4eyP4o8j+1TvzinevGcg6UBuAZQdGNB56dlBe0EXLPqBfwDuLaRWtdBpBvup8DeJVo6gA/lWbyRmcw4pWRL+p5HnJcndaRo72c5X4tLAECj3aWli5wP+SZ9ydkYUotyjUACwDMPvEDezIpARkxgUftD5ImzfCb8UjYMA3L8VsPbk6Hx421GoV3oQP+msYZmjxyFJwrVs6jZGZ8clnvk1fvNzFNHquL8/yWyViPjZ683A4C8NIVFTcEXSSLpTHa8iWYKUZiFBkUIVZpYvhxUYGaeuK6Ea7v8pwmvORMQEWhwZzZ59nmXrCS1a4tBJgpJaGQ+OW0WwG9Gyv1Rcs//fxgo6lxkYMJhNbq2VGUwOLOmuCuFeDVXgsHd/yCKac/YEJWNKiGHPXf6oSIXvqTwmtzQK1Hki3A23QFYiVkFmqdlETvtqbh+iHxLU7gVfU+/QL/c5n8OWWLuRLR2PhDFKB+QsKfAluAw1ExSaKCTVe6oZJwScXfAtxJkQeJ0Ir9shNKfmsm6J5XInpzMPNHtCKlrB/Wnx6FpnfKi0+9CLLuP88nr/NpK8M0IsSgTFI47r5X2whQ2Ajok5JRFVnvwQTrYKspBOk+rKX2l7O05r5vkItlkRLwNLfFrT/MDUYUK8y+DIPJTaKyBiSOoEa6kw+5Y2dNHMV3tHmYdeM9CCdvKNKcK5M7v+bu1U4E5BZtBoUH8Mus8MbQQkgilxvfGMIuto0Y8iIBHsEH1Wq4L4y6Wb+We+HQnkE36ZkNR/uNkEi1p0q
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflare-tunnel
