apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    base-url: "https://ntfy.mbianchi.me"
    listen-http: ":80"
    cache-file: "/var/cache/ntfy/cache.db"
    cache-duration: "12h"
    auth-file: "/var/lib/ntfy/user.db"
    auth-default-access: "deny-all"
    behind-proxy: true
    attachment-cache-dir: "/var/cache/ntfy/attachments"
    attachment-total-size-limit: "5G"
    attachment-file-size-limit: "15M"
    keepalive-interval: "45s"
